#######################################################
# 
# DatabaseInterface.py
# Python implementation of the Interface DatabaseInterface
# Generated by Enterprise Architect
# Created on:      27-Feb-2022 17:22:51
# Original author: janbi
# 
#######################################################
from src.event.EventInterface import EventInterface

class DatabaseInterface:
    def save_event(event):
        pass