#######################################################
# 
# SingleFileDatabase.py
# Python implementation of the Class SingleFileDatabase
# Generated by Enterprise Architect
# Created on:      06-Mar-2022 12:13:40
# Original author: janbi
# 
#######################################################
from srcv import EventInterface
from srcv import DatabaseInterface

class SingleFileDatabase(DatabaseInterface):
    def save_event(event):
        pass