#######################################################
# 
# SingleFileDatabase.py
# Python implementation of the Class SingleFileDatabase
# Generated by Enterprise Architect
# Created on:      27-Feb-2022 17:22:51
# Original author: janbi
# 
#######################################################
from src.event.EventInterface import EventInterface
from src.database.DatabaseInterface import DatabaseInterface

class SingleFileDatabase(DatabaseInterface):
    def save_event(event):
        pass