#######################################################
# 
# EventInterface.py
# Python implementation of the Interface EventInterface
# Generated by Enterprise Architect
# Created on:      27-Feb-2022 17:22:51
# Original author: janbi
# 
#######################################################
from src.event.participant.ParticipantInterface import ParticipantInterface
from src.event.result.ResultInterface import ResultInterface

class EventInterface:
    m_ParticipantInterface= ParticipantInterface()

    m_ResultInterface= ResultInterface()

    def create(start_time, name):
        pass