#######################################################
# 
# Game.py
# Python implementation of the Interface Game
# Generated by Enterprise Architect
# Created on:      06-Mar-2022 12:13:40
# Original author: janbi
# 
#######################################################
from srcv import EventInterface

class Game(EventInterface):
    def create(start_time, name):
        pass