#######################################################
# 
# Game.py
# Python implementation of the Interface Game
# Generated by Enterprise Architect
# Created on:      27-Feb-2022 17:22:51
# Original author: janbi
# 
#######################################################
from src.event.EventInterface import EventInterface

class Game(EventInterface):
    def create(start_time, name):
        pass