#######################################################
# 
# TeamGame.py
# Python implementation of the Class TeamGame
# Generated by Enterprise Architect
# Created on:      06-Mar-2022 12:13:40
# Original author: janbi
# 
#######################################################
from srcv import EventInterface
from srcv import Game

class TeamGame(Game):
    def create(start_time, name):
        pass

    def create(start_time, name):
        pass