#######################################################
# 
# TeamGame.py
# Python implementation of the Class TeamGame
# Generated by Enterprise Architect
# Created on:      27-Feb-2022 17:22:51
# Original author: janbi
# 
#######################################################
from src.event.EventInterface import EventInterface
from src.event.Game import Game

class TeamGame(Game):
    def create(start_time, name):
        pass

    def create(start_time, name):
        pass

class TeamGame:
    pass