#######################################################
# 
# Discipline.py
# Python implementation of the Class Discipline
# Generated by Enterprise Architect
# Created on:      06-Mar-2022 12:13:39
# Original author: janbi
# 
#######################################################


class Discipline:
    pass