#######################################################
# 
# FootballGame.py
# Python implementation of the Class FootballGame
# Generated by Enterprise Architect
# Created on:      06-Mar-2022 12:13:39
# Original author: janbi
# 
#######################################################
from srcv import TeamGame

class FootballGame(TeamGame):
    def give_yellow_card(player):
        pass