#######################################################
# 
# Football.py
# Python implementation of the Class Football
# Generated by Enterprise Architect
# Created on:      06-Mar-2022 12:13:39
# Original author: janbi
# 
#######################################################
from srcv import Discipline

class Football(Discipline):
    pass