#######################################################
# 
# FootballPlayer.py
# Python implementation of the Class FootballPlayer
# Generated by Enterprise Architect
# Created on:      06-Mar-2022 12:13:40
# Original author: janbi
# 
#######################################################
from srcv import Discipline
from srcv import Player

class FootballPlayer(Player):
    discipline = Football