#######################################################
# 
# LineUps.py
# Python implementation of the Class LineUps
# Generated by Enterprise Architect
# Created on:      06-Mar-2022 12:13:40
# Original author: janbi
# 
#######################################################
from srcv import FootballGame
from srcv import Substitution

class LineUps:
    m_FootballGame= FootballGame()

    m_Substitution= Substitution()

    def make_substitution(player_in, player_out):
        """Return True if substitution went successfully.
        """
        pass