#######################################################
# 
# Player.py
# Python implementation of the Class Player
# Generated by Enterprise Architect
# Created on:      06-Mar-2022 12:13:40
# Original author: janbi
# 
#######################################################


class Player:
    m_Player= Player()
