#######################################################
# 
# Substitution.py
# Python implementation of the Class Substitution
# Generated by Enterprise Architect
# Created on:      06-Mar-2022 12:13:40
# Original author: janbi
# 
#######################################################
from srcv import Player

class Substitution:
    pass