#######################################################
# 
# Coach.py
# Python implementation of the Class Coach
# Generated by Enterprise Architect
# Created on:      06-Mar-2022 12:13:39
# Original author: janbi
# 
#######################################################


class Coach:
    pass