#######################################################
# 
# ParticipantInterface.py
# Python implementation of the Interface ParticipantInterface
# Generated by Enterprise Architect
# Created on:      27-Feb-2022 17:22:51
# Original author: janbi
# 
#######################################################


class ParticipantInterface:
    def name():
        pass