#######################################################
# 
# Team.py
# Python implementation of the Class Team
# Generated by Enterprise Architect
# Created on:      27-Feb-2022 17:22:51
# Original author: janbi
# 
#######################################################
from src.event.participant.ParticipantInterface import ParticipantInterface

class Team(ParticipantInterface):
    def name():
        pass