#######################################################
# 
# Team.py
# Python implementation of the Class Team
# Generated by Enterprise Architect
# Created on:      06-Mar-2022 12:13:40
# Original author: janbi
# 
#######################################################
from srcv import ParticipantInterface
from srcv import TeamGame
from srcv import Coach

class Team(ParticipantInterface):
    game= TeamGame()

    m_Coach= Coach()

    def name():
        pass